language: python

# django 1.9 is only supported on py27 and py35
# django 1.8 is the first realease supporting py35
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-1.7
    - python: 2.7
      env: TOXENV=py27-1.8
    - python: 2.7
      env: TOXENV=py27-1.9
    - python: 3.3
      env: TOXENV=py33-1.7
    - python: 3.3
      env: TOXENV=py33-1.8
    - python: 3.4
      env: TOXENV=py34-1.7
    - python: 3.4
      env: TOXENV=py34-1.8
    - python: 3.4
      env: TOXENV=py34-1.9
    - python: 3.5
      env: TOXENV=py35-1.8
    - python: 3.5
      env: TOXENV=py35-1.9
    - python: 2.7
      env: TOXENV=py27-master
    - python: 3.5
      env: TOXENV=py35-master

  allow_failures:
      - env: TOXENV=py27-master
      - env: TOXENV=py35-master
install:
  - pip install tox
  - pip install python-coveralls
script:
  - tox

after_success:
    coveralls
