dist: xenial
language: python
cache:
    pip: true
addons:
    apt:
       packages:
           - enchant
           - myspell-en-us

install:
  - pip install tox coverage

script:
  - tox

matrix:
  include:
    - { python: 3.5, env: TOXENV=py35-2.1 }
    - { python: 3.5, env: TOXENV=py35-2.2 }
    - { python: 3.6, env: TOXENV=py36-2.1 }
    - { python: 3.6, env: TOXENV=py36-2.2 }
    - { python: 3.6, env: TOXENV=py36-3.0 }
    - { python: 3.6, env: TOXENV=py36-master }
    - { python: 3.7, env: TOXENV=py37-2.1 }
    - { python: 3.7, env: TOXENV=py37-2.2 }
    - { python: 3.7, env: TOXENV=py37-3.0 }
    - { python: 3.7, env: TOXENV=py37-master }
    - { python: 3.6, env: TOXENV=docs }
    - { python: 3.6, env: TOXENV=flake8 }
    - { python: 3.6, env: TOXENV=isort }
    - { python: 3.6, env: TOXENV=black }

  # we allow failures for versions which are not yet released:
  allow_failures:
      - env: TOXENV=py35-master
      - env: TOXENV=py36-master
      - env: TOXENV=py37-master
      - env: TOXENV=py38-master

after_success:
    - pip combine --amend
    - pip report -m
    - pip install codecov
    - codecov
