language: python
python:
  - 3.3
env:
  - TOX_ENV=py33-dj18
  - TOX_ENV=py33-dj16
  - TOX_ENV=py33-dj15
  - TOX_ENV=py32-dj16
  - TOX_ENV=py32-dj15
  - TOX_ENV=py27-dj16
  - TOX_ENV=py27-dj15
  - TOX_ENV=py27-dj14
  - TOX_ENV=py27-dj13
  - TOX_ENV=py27-dj12
  - TOX_ENV=py26-dj16
  - TOX_ENV=py26-dj15
  - TOX_ENV=py26-dj14
  - TOX_ENV=py26-dj13
  - TOX_ENV=py26-dj12
install:
  - pip install tox
script:
  - tox -e $TOX_ENV